apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: log-producer
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  host: log-producer
  service:
    name: log-producer
    port: 80
