apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: log-producer
  labels:
    app: log-producer
spec:
  scaleConfig:
    maxReplicas: 1
    minReplicas: 1
  runtime: nodejs18
  template:
    labels:
      app: log-producer
  source:
    inline:
      source: |-
        module.exports = {
            main: function (event, context) {
                var headers=event.extensions.request.headers
                var crypto = require("crypto");
                console.log(JSON.stringify({"@timestamp":"2023-06-14T13:19:25.830Z","log.level":"debug","message":"< Received getCurrentWeather response from http://api.weatherapi.com/v1","ecs":{"version":"1.6.0"}}))
                return "Log triggered with request-id " + event.extensions.request.headers["x-request-id"]
            }
        }
      dependencies: |-
        {  
          "name": "log-producer",
          "version": "1.0.0",
          "dependencies":{
          }
        }
