apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: null
  name: event-receiver
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.acme.payload.sanitised.v1
  protocol: ""
  protocolsettings: {}
  sink: http://svc-c.default.svc.cluster.local