apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: svc-b
  labels:
    app: svc-b
spec:
  scaleConfig:
    maxReplicas: 1
    minReplicas: 1
  runtime: nodejs14
  template:
    labels:
      app: svc-b
  source:
    inline:
      source: |-
        const axios = require("axios");
        module.exports = {
            main: async function (event, context) {
              let traceId=event.extensions.request.headers['x-b3-traceid']
              console.debug(`level=debug traceId=${traceId} message=Event data: ${JSON.stringify(event.data)}`);

              if(Date.now() % 2 == 0){
                res = event.extensions.response;
                res.writeHead(503,{'Content-Type': 'text/plain'});
                res.write('Bad timing!');
                res.end();
                console.error(`level=error traceId=${traceId} message=Bad timing`);
                return
              }

              let response = await axios.post("http://svc-c.default:80", event.data);
              console.info(`level=info traceId=${traceId} message=Called svc-c`);
              return response.data
          }
        };
      dependencies: |-
        {  
          "name": "svc-b",
          "version": "1.0.0",
          "dependencies":{
            "axios": "^0.19.0"
          }
        }